---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deployment
  labels:
    tier: web
    app: myweb
spec:
  selector:
    matchLabels:
      app: myweb
  replicas: 6
  template:
    metadata:
      name: python
      labels:
        app: myweb
    spec:
      containers:
        - name: myweb
          image: bnktch/web